name: Stats

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2
      - name: Stup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.11'
      - name: Run script
        run: python ./Roadmap/stats.py
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: Update stats
          commit_user_name: Hector [GitHub Actions]
          commit_user_email: hadazar3@gmail.com
          commit_author: Hadazar
        
